# F4INU ham radio projects and notes
petrus <f4inu@tuta.io>
12, 2024-02-15: Asciidoc rewrite
:toc: left
:stylesheet: ./boot-slate.css

## link:f4inu/[About me]
Copy of my qrz.com page.


## link:adsb/[ADS-B ground plane antenna]
2015-09-07
Construction d'une ground plane 1090MHz pour réception ads-b.

## link:inmarsat/[Exploring Inmarsat BGAN]
2019-07-14
Exploration d'un terminal BGAN Inmarsat Thrane & Thrane Explorer 700

## link:pied/[Mast spike mount]
2020-09-26
Bricolage d'un pied de mat d'antenne

## link:magloop/[Magloop]
2020-11-08
Construction d'une antenne magloop

## link:wsjtx/[WSJT-X]
2020-11-13
Réception FT8 avec WSJT-X et SDR

## link:usb/[USB & udev]
2021-06-07
Règles udev pour éviter la confusion entre multiples périphériques

## link:ghetto-squalo/[Ghetto-Squalo]
2022-05-06
Dipole filaire replié entre halo et cobweb

## link:solar/[Solar]
2022-08-15
Alimentation solaire

## link:dowap/[DOWaP]
2022-09-19
Days Operating Without any Power

## link:icom/[Icom]
2022-11-06
Bidouilles pour radios Icom

## link:anytone/[Anytone PTT]
2023-03-27
Utilisation d'un bouton Bluetooth PTT Anytone BP-02 avec un ordi
